# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja-JP"
# グローバルな指示（トーンやルールなど）
tone_instructions: "経験豊富なシニアエンジニアとして、簡潔かつ丁寧にレビューしてください。コードの品質だけでなく、可読性や保守性についても指摘してください。"

early_access: true

reviews:
  profile: assertive
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  collapse_walkthrough: true
  auto_apply_labels: true
  # ツール系は自動検出されるため、明示的に無効化したい場合以外は記述不要なことが多いです。
  # 独自のチェックを強制したい場合は残してください。
  tools:
    eslint:
      enabled: true
