/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.workers.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareWorkerBindings cloudflare-env.d.ts` (hash: 248e5a3444504ade943fe066b8c516cc)
interface __BaseEnv_CloudflareWorkerBindings {
	AKYO_KV: KVNamespace;
	AKYO_BUCKET: R2Bucket;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	NEXT_TAG_CACHE_D1: D1Database;
	IMAGES: ImagesBinding;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	NEXT_PUBLIC_APP_URL: string;
	NEXT_PUBLIC_SITE_URL: string;
	NEXT_PUBLIC_USE_JSON_DATA: string;
	GITHUB_REPO_OWNER: string;
	GITHUB_REPO_NAME: string;
	GITHUB_BRANCH: string;
	GITHUB_CSV_PATH_JA: string;
	NEXT_PUBLIC_USE_KV_DATA: string;
	NEXT_PUBLIC_R2_BASE: string;
	NEXT_CACHE_DO_QUEUE: DurableObjectNamespace<import("./cloudflare-worker").DOQueueHandler>;
	WORKER_SELF_REFERENCE: Service<typeof import("./cloudflare-worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./cloudflare-worker");
		durableNamespaces: "DOQueueHandler";
	}
	interface Env extends __BaseEnv_CloudflareWorkerBindings {}
}
interface CloudflareWorkerBindings extends __BaseEnv_CloudflareWorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_APP_URL" | "NEXT_PUBLIC_SITE_URL" | "NEXT_PUBLIC_USE_JSON_DATA" | "GITHUB_REPO_OWNER" | "GITHUB_REPO_NAME" | "GITHUB_BRANCH" | "GITHUB_CSV_PATH_JA" | "NEXT_PUBLIC_USE_KV_DATA" | "NEXT_PUBLIC_R2_BASE">> {}
}
