/**
 * API Route: Category management
 *
 * GET  /api/categories  → every category with EN/KO names and row counts (admin or owner)
 * POST /api/categories  → { action: 'create' | 'translate' | 'rename' | 'merge' | 'delete', ... }
 *   create / translate: admin or owner. rename / merge / delete: owner only.
 *
 * Each POST is one commit on main touching data/akyo-data-ja.csv,
 * data/category-translations.json and src/lib/category-colors.json as needed. EN/KO CSVs
 * and JSON are regenerated by the Sync JSON Data workflow after the commit.
 */

import { connection } from 'next/server';
import { ensureAdminRequest, jsonError } from '@/lib/api-helpers';
import { buildCategoryListResponse, processCategoryRequest } from '@/lib/category-api';

export async function GET(request: Request) {
  await connection();
  // Same-origin GET: the response is unreadable cross-site, so the Origin check is not needed.
  const guard = await ensureAdminRequest(request, { requireOrigin: false });
  if ('response' in guard) return guard.response;
  return buildCategoryListResponse();
}

export async function POST(request: Request) {
  await connection();
  const guard = await ensureAdminRequest(request);
  if ('response' in guard) return guard.response;
  const text = await request.text();
  if (text.length > 100_000) return jsonError('リクエストが大きすぎます', 413);
  let body: unknown;
  try {
    body = JSON.parse(text);
  } catch {
    return jsonError('JSONの解析に失敗しました', 400);
  }
  return processCategoryRequest(body, guard.session.role);
}
