/**
 * Korean nickname translation map
 * Japanese nickname → Korean nickname
 *
 * Rules:
 *  - "Akyo" stays as-is in all cases
 *  - The prefix part (○○) is translated to Korean
 *  - Japanese source is primary, English is reference
 *  - Proper nouns, product names, and version suffixes kept as-is
 *  - Special forms (あきょ, きょ, etc.) use matching Korean readings
 */

const NICKNAME_MAP = {
  // === 0001–0010: Mint Chocolate series ===
  オリジンAkyo: '오리진 Akyo',
  チョコミントAkyo: '초코민트 Akyo',
  赤チョコミントAkyo: '빨간 초코민트 Akyo',
  緑チョコミントAkyo: '초록 초코민트 Akyo',
  青チョコミントAkyo: '파란 초코민트 Akyo',
  黄チョコミントAkyo: '노란 초코민트 Akyo',
  黒チョコミントAkyo: '검정 초코민트 Akyo',
  白チョコミントAkyo: '하얀 초코민트 Akyo',
  灰チョコミントAkyo: '회색 초코민트 Akyo',
  ミニチョコミントAkyo: '미니 초코민트 Akyo',

  // === 0011–0020: Super / unique ===
  スーパー汎用Akyo: '슈퍼 범용 Akyo',
  スーパースタッフAkyo: '슈퍼 스태프 Akyo',
  スーパーワープAkyo: '슈퍼 워프 Akyo',
  スーパーフライング運送Akyo: '슈퍼 플라잉 운송 Akyo',
  ランAkyo: '달리기 Akyo',
  バルブAkyo: '밸브 Akyo',
  'N/A': 'N/A',
  ヒューマノイドAkyo: '휴머노이드 Akyo',
  キツネツキ式狐Akyo: '키츠네츠키식 여우 Akyo',
  キツネツキ式幽霊狐Akyo: '키츠네츠키식 유령 여우 Akyo',

  // === 0021–0030 ===
  キツネツキ式溶け狐Akyo: '키츠네츠키식 녹은 여우 Akyo',
  キツネツキ式足長狐Akyo: '키츠네츠키식 다리긴 여우 Akyo',
  ウーガーイーツAkyo: '우가이츠 Akyo',
  アキョンゲリヲンAkyo: '아쿄엔겔리온 Akyo',
  アキョスAkyo: '아쿄스 Akyo',
  冬虫Akyo: '동충하초 Akyo',
  スプーンフォークAkyo: '숟가락포크 Akyo',
  'ロボットAkyo（サンプル）': '로봇 Akyo（샘플）',
  ダッフルコートAkyo: '더플코트 Akyo',
  ダウンベストAkyo: '다운조끼 Akyo',

  // === 0031–0040 ===
  レイマーチAkyo: '레이마치 Akyo',
  ルックAkyo: '룩 Akyo',
  神秘のAkyo: '신비의 Akyo',
  ウミウシAkyo: '갯민숭달팽이 Akyo',
  神秘のウミウシAkyo: '신비의 갯민숭달팽이 Akyo',
  ねおウミウシAkyo: '네오 갯민숭달팽이 Akyo',
  ウツボカズラAkyo: '벌레잡이통풀 Akyo',
  トゥーンAkyo: '툰 Akyo',
  サボテンAkyo: '선인장 Akyo',
  ローストAkyo: '로스트 Akyo',

  // === 0041–0050 ===
  キヌガサAkyo: '망태버섯 Akyo',
  '64ポリゴンAkyo': '64 폴리곤 Akyo',
  ミナミコアリクイAkyo: '작은개미핥기 Akyo',
  苔Akyo: '이끼 Akyo',
  木目Akyo: '나뭇결 Akyo',
  大理石Akyo: '대리석 Akyo',
  こんにゃくAkyo: '곤약 Akyo',
  UFOAkyo: 'UFO Akyo',
  '調査船MU-KYO': '조사선 MU-KYO',
  JustやきいもAkyo: 'Just 군고구마 Akyo',

  // === 0051–0060 ===
  レモンAkyo: '레몬 Akyo',
  ヤギAkyo: '염소 Akyo',
  デビルヤギAkyo: '데빌 염소 Akyo',
  チーズ牛丼Akyo: '치즈규동 Akyo',
  皮Akyo: '가죽 Akyo',
  肉Akyo: '고기 Akyo',
  トピアリーAkyo: '토피어리 Akyo',
  サイバーAkyo: '사이버 Akyo',
  陸自Akyo: '육자대 Akyo',
  農kyo: '농kyo',

  // === 0061–0070 ===
  スギゴケAkyo: '삼나무이끼 Akyo',
  マンボーAkyo: '개복치 Akyo',
  ワイルズAkyo: '와일즈 Akyo',
  デニムAkyo: '데님 Akyo',
  マグマAkyo: '마그마 Akyo',
  監視者Akyo: '감시자 Akyo',
  ステルスAkyo: '스텔스 Akyo',
  TIAシャツAkyo: 'TIA 셔츠 Akyo',
  エラーAkyo: '에러 Akyo',
  ねこですAkyo: '고양이입니다 Akyo',

  // === 0071–0080 ===
  モナリザAkyo: '모나리자 Akyo',
  テレビAkyo: 'TV Akyo',
  ずんだもんAkyo: '즌다몬 Akyo',
  ゆるめのアヌビスAkyo: '느긋한 아누비스 Akyo',
  選挙ポスターAkyo: '선거포스터 Akyo',
  おさとうAkyo: '설탕 Akyo',
  ベクシンスキーAkyo: '벡신스키 Akyo',
  タレットAkyo: '터렛 Akyo',
  カニになりたいAkyo: '게가 되고 싶은 Akyo',
  ルネAkyo: '르네 Akyo',

  // === 0081–0090 ===
  カーバンクルAkyo: '카벙클 Akyo',
  'DDT-AKYO': 'DDT-AKYO',
  もぐらAkyo: '두더지 Akyo',
  ゾウクラゲAkyo: '코끼리해파리 Akyo',
  タコスAkyo: '타코스 Akyo',
  もしもピアノになれたならAkyo: '만약 피아노가 될 수 있다면 Akyo',
  スク水Akyo: '스쿨미즈 Akyo',
  チンアナゴAkyo: '가든일 Akyo',
  うねAkyo: '물결 Akyo',
  分身Akyo: '분신 Akyo',

  // === 0091–0100 ===
  ステンドグラスAkyo: '스테인드글라스 Akyo',
  消えるAkyo: '사라지는 Akyo',
  UV展開Akyo: 'UV 전개 Akyo',
  色変更Akyo: '색 변경 Akyo',
  ランダムノイズAkyo: '랜덤 노이즈 Akyo',
  ゆがむAkyo: '왜곡 Akyo',
  モザイクAkyo: '모자이크 Akyo',
  落ちそうAkyo: '떨어질 것 같은 Akyo',
  波動Akyo: '파동 Akyo',
  ヒプノシスAkyo: '히프노시스 Akyo',

  // === 0101–0110 ===
  吸い込まれるAkyo: '빨려드는 Akyo',
  グリッチAkyo: '글리치 Akyo',
  ボクセルAkyo: '복셀 Akyo',
  レインボーAkyo: '레인보우 Akyo',
  サウAkyo: '사우 Akyo',
  '消えるAkyo3.0': '사라지는 Akyo 3.0',
  サラマンダーAkyo: '샐러맨더 Akyo',
  メルトAkyo: '멜트 Akyo',
  リアルAkyo: '리얼 Akyo',
  デブAkyo: '뚱뚱 Akyo',

  // === 0111–0120 ===
  天使Akyo: '천사 Akyo',
  さいばーあきょう: '사이버 아쿄',
  テルミンAkyo: '테르민 Akyo',
  ふわふわAkyo: '폭신폭신 Akyo',
  お祭りAkyo: '축제 Akyo',
  ひなたAkyo: '히나타 Akyo',
  メジェドAkyo: '메제드 Akyo',
  アマゴを背負うAkyo: '아마고를 짊어진 Akyo',
  カツオを背負うAkyo: '가다랑어를 짊어진 Akyo',
  草Akyo: '풀 Akyo',

  // === 0121–0130 ===
  キラキラAkyo: '반짝반짝 Akyo',
  後光がなんかすごいAkyo: '후광이 뭔가 대단한 Akyo',
  泡Akyo: '거품 Akyo',
  回折格子Akyo: '회절격자 Akyo',
  色胞光学迷彩Akyo: '색소포 광학미채 Akyo',
  ヒョウモントカゲモドキAkyo: '레오파드 게코 Akyo',
  ヤンバルクイナAkyo: '얀바루쿠이나 Akyo',
  パーティクルAkyo: '파티클 Akyo',
  焼きAkyo: '구운 Akyo',
  ぼんじりAkyo: '봉지리 Akyo',

  // === 0131–0140 ===
  踊り子Akyo: '무용수 Akyo',
  グッチAkyo: '구찌 Akyo',
  すあまAkyo: '스아마 Akyo',
  アメジストAkyo: '자수정 Akyo',
  段ボールAkyo: '골판지 Akyo',
  しいたけAkyo: '표고버섯 Akyo',
  それんAkyo: '소련 Akyo',
  じょんAkyo: '종 Akyo',
  雪だるまAkyo: '눈사람 Akyo',
  窓Akyo: '창문 Akyo',

  // === 0141–0150 ===
  ケーキAkyo: '케이크 Akyo',
  みかんAkyo: '귤 Akyo',
  おんがくAkyo: '음악 Akyo',
  かたつむりAkyo: '달팽이 Akyo',
  'めんしすAkyo？': '멘시스 Akyo？',
  ベニスAkyo: '베니스 Akyo',
  νAkyo: 'ν Akyo',
  J2m3Akyo: 'J2m3 Akyo',
  'virtual bayroi4Akyo': 'virtual bayroi4 Akyo',
  HinyoAkyo: 'Hinyo Akyo',

  // === 0151–0160 ===
  うしAkyo: '소 Akyo',
  ポンチョAkyo: '판초 Akyo',
  ハロウィンAkyo: '할로윈 Akyo',
  工事Akyo: '공사 Akyo',
  タオルAkyo: '타월 Akyo',
  アロハAkyo: '알로하 Akyo',
  トナカイAkyo: '순록 Akyo',
  サンタAkyo: '산타 Akyo',
  きつねAkyo: '여우 Akyo',
  オコジョAkyo: '족제비 Akyo',

  // === 0161–0170 ===
  きつねAkyo2: '여우 Akyo 2',
  すしAkyo: '초밥 Akyo',
  くまAkyo: '곰 Akyo',
  くまAkyo2: '곰 Akyo 2',
  かがみもちAkyo: '거울떡 Akyo',
  ねずみAkyo: '쥐 Akyo',
  ナスAkyo: '가지 Akyo',
  みかんちゃんAkyo: '귤쨩 Akyo',
  どらごんAkyo: '드래곤 Akyo',
  おにAkyo: '도깨비 Akyo',

  // === 0171–0180 ===
  はーふAkyo: '하프 Akyo',
  かっぱAkyo: '갓파 Akyo',
  たぬきAkyo: '너구리 Akyo',
  バーガーAkyo: '버거 Akyo',
  ちくわAkyo: '치쿠와 Akyo',
  ナースAkyo: '간호사 Akyo',
  マフラーAkyo: '목도리 Akyo',
  ペンギンAkyo: '펭귄 Akyo',
  サメAkyo: '상어 Akyo',
  うさぎAkyo: '토끼 Akyo',

  // === 0181–0190 ===
  たんぽぽAkyo: '민들레 Akyo',
  シスターAkyo: '수녀 Akyo',
  シスターきつねAkyo: '수녀 여우 Akyo',
  郵便Akyo: '우편 Akyo',
  プリンAkyo: '푸딩 Akyo',
  だいこんAkyo: '무 Akyo',
  // 0187 うしAkyo → same as 0151
  コーヒーAkyo: '커피 Akyo',
  インディアンAkyo: '인디언 Akyo',
  トロピカルAkyo1: '트로피컬 Akyo 1',

  // === 0191–0200 ===
  トロピカルAkyo2: '트로피컬 Akyo 2',
  トロピカルAkyo3: '트로피컬 Akyo 3',
  にんじゃAkyo: '닌자 Akyo',
  ばななAkyo: '바나나 Akyo',
  ハリネズミAkyo: '고슴도치 Akyo',
  朝顔Akyo: '나팔꽃 Akyo',
  赤飯Akyo: '팥밥 Akyo',
  バニーAkyo: '버니 Akyo',
  アルパカAkyo: '알파카 Akyo',
  アルパカAkyo2: '알파카 Akyo 2',

  // === 0201–0210 ===
  とろろAkyo: '토로로 Akyo',
  とろろAkyo2: '토로로 Akyo 2',
  ゆかたAkyo: '유카타 Akyo',
  ふぉーるAkyo: '폴 Akyo',
  ひよこAkyo: '병아리 Akyo',
  海辺Akyo: '해변 Akyo',
  あしがるAkyo: '아시가루 Akyo',
  'ゆうれいAkyo/ゴーストAkyo': '유령 Akyo/고스트 Akyo',
  フランケンAkyo: '프랑켄 Akyo',
  ミイラAkyo: '미라 Akyo',

  // === 0211–0220 ===
  さつまいもAkyo: '고구마 Akyo',
  コートきつねAkyo: '코트 여우 Akyo',
  ししまいAkyo: '사자춤 Akyo',
  巫女きつねAkyo: '무녀 여우 Akyo',
  ひつじAkyo: '양 Akyo',
  ローポリきつねAkyo: '로우폴리 여우 Akyo',
  amongAkyo: 'among Akyo',
  'エジプトAkyo/ファラオAkyo': '이집트 Akyo/파라오 Akyo',
  たいやききつねAkyo: '붕어빵 여우 Akyo',
  いぬAkyo: '개 Akyo',

  // === 0221–0230 ===
  とうもろこしAkyo: '옥수수 Akyo',
  かいぞくAkyo: '해적 Akyo',
  きつねAkyoV2: '여우 Akyo V2',
  にんじんAkyo: '당근 Akyo',
  おそうじAkyo: '청소 Akyo',
  とらAkyo: '호랑이 Akyo',
  ふりそできつねAkyo: '후리소데 여우 Akyo',
  九尾きつねAkyo: '구미호 Akyo',
  フライAkyo: '튀김 Akyo',
  メイドきつねAkyo: '메이드 여우 Akyo',

  // === 0231–0240 ===
  かき氷Akyo: '빙수 Akyo',
  歩兵Akyo: '보병 Akyo',
  メガネAkyo: '안경 Akyo',
  白菜Akyo: '배추 Akyo',
  たけのこAkyo: '죽순 Akyo',
  ピザAkyo: '피자 Akyo',
  ドラキュラAkyo: '드라큘라 Akyo',
  おばけきつねAkyo: '유령 여우 Akyo',
  アイドルきつねAkyo: '아이돌 여우 Akyo',
  焼き芋Akyo: '군고구마 Akyo',

  // === 0241–0250 ===
  イスAkyo: '의자 Akyo',
  '旅きつねAkyo/ポンチョきつねAkyo': '여행 여우 Akyo/판초 여우 Akyo',
  ねこAkyo: '고양이 Akyo',
  ハスキーAkyo: '허스키 Akyo',
  おしるこAkyo: '단팥죽 Akyo',
  きつねうどんAkyo: '유부우동 Akyo',
  さくらきつねAkyo: '벚꽃 여우 Akyo',
  夏きつねAkyo: '여름 여우 Akyo',
  キャベツAkyo: '양배추 Akyo',
  スイカAkyo: '수박 Akyo',

  // === 0251–0260 ===
  うまAkyo: '말 Akyo',
  ホットドッグAkyo: '핫도그 Akyo',
  現場ねこAkyo: '현장 고양이 Akyo',
  とうがらしAkyo: '고추 Akyo',
  トリケラAkyo: '트리케라 Akyo',
  ステゴAkyo: '스테고 Akyo',
  プテラAkyo: '프테라 Akyo',
  ホットきつねAkyo: '핫 여우 Akyo',
  ティラノAkyo: '티라노 Akyo',
  パンダAkyo: '판다 Akyo',

  // === 0261–0270 ===
  パインAkyo: '파인애플 Akyo',
  へびAkyo: '뱀 Akyo',
  ペーパーAkyo: '페이퍼 Akyo',
  ねまききつねAkyo: '잠옷 여우 Akyo',
  ホットケーキAkyo: '핫케이크 Akyo',
  白玉Akyo: '시라타마 Akyo',
  ポンデAkyo: '폰데 Akyo',
  ようかんAkyo: '양갱 Akyo',
  ねまきねこAkyo: '잠옷 고양이 Akyo',
  カステラAkyo: '카스테라 Akyo',

  // === 0271–0280 ===
  タコさんAkyo: '문어씨 Akyo',
  マヨAkyo: '마요 Akyo',
  ギョーザAkyo: '만두 Akyo',
  アイスAkyo: '아이스크림 Akyo',
  ラーメンAkyo: '라면 Akyo',
  バッテリーAkyo: '배터리 Akyo',
  だんごAkyo: '경단 Akyo',
  LpackAkyo: 'Lpack Akyo',
  フライドポテトAkyo: '감자튀김 Akyo',
  サメAkyo2: '상어 Akyo 2',

  // === 0281–0290 ===
  あざらしAkyo: '물개 Akyo',
  キッズAkyo: '키즈 Akyo',
  納豆Akyo: '낫토 Akyo',
  クラゲAkyo: '해파리 Akyo',
  消しゴムAkyo: '지우개 Akyo',
  キョンシーAkyo: '강시 Akyo',
  シャンプーAkyo: '샴푸 Akyo',
  ブラキオAkyo: '브라키오 Akyo',
  こいのぼりAkyo: '잉어깃발 Akyo',
  かしわもちAkyo: '카시와모치 Akyo',

  // === 0291–0300 ===
  プレシオAkyo: '플레시오 Akyo',
  てるてるAkyo: '테루테루 Akyo',
  ちょうちんAkyo: '초롱 Akyo',
  いのししAkyo: '멧돼지 Akyo',
  ひまわりAkyo: '해바라기 Akyo',
  トーストきつねAkyo: '토스트 여우 Akyo',
  カンガルーAkyo: '캥거루 Akyo',
  村Akyo: '마을 Akyo',
  うさぎAkyo2: '토끼 Akyo 2',
  冒険きつねAkyo: '모험 여우 Akyo',

  // === 0301–0310 ===
  コックきつねAkyo: '요리사 여우 Akyo',
  警察きつねAkyo: '경찰 여우 Akyo',
  キーウイAkyo: '키위새 Akyo',
  換毛期きつねAkyo: '환모기 여우 Akyo',
  プリンアイスAkyo: '푸딩 아이스 Akyo',
  宇宙きつねAkyo: '우주 여우 Akyo',
  すずめAkyo: '참새 Akyo',
  消防きつねAkyo: '소방 여우 Akyo',
  サカバンAkyo: '사카반 Akyo',
  わらびもちAkyo: '와라비모치 Akyo',

  // === 0311–0320 ===
  あじさいAkyo: '수국 Akyo',
  ブロッコリーAkyo: '브로콜리 Akyo',
  医者きつねAkyo: '의사 여우 Akyo',
  英国きつねAkyo: '영국 여우 Akyo',
  黒板消しAkyo: '칠판지우개 Akyo',
  すしAkyo2: '초밥 Akyo 2',
  オムライスAkyo: '오므라이스 Akyo',
  ぞうAkyo: '코끼리 Akyo',
  JKきつねAkyo: 'JK 여우 Akyo',
  JKチアきつねAkyo: 'JK 치어 여우 Akyo',

  // === 0321–0330 ===
  ねぎAkyo: '파 Akyo',
  たぬきそばAkyo: '너구리소바 Akyo',
  うな重Akyo: '장어덮밥 Akyo',
  スイカアイスAkyo: '수박 아이스 Akyo',
  レッサーパンダAkyo: '레서판다 Akyo',
  レッサーパンダAkyo2: '레서판다 Akyo 2',
  ようせつAkyo: '용접 Akyo',
  ワイバーンAkyo: '와이번 Akyo',
  冬きつねAkyo: '겨울 여우 Akyo',
  フルーツきつねAkyo: '과일 여우 Akyo',

  // === 0331–0340 ===
  おじぞうAkyo: '지장보살 Akyo',
  '足軽Akyo2／侍Akyo': '아시가루 Akyo 2／사무라이 Akyo',
  侍きつねAkyo: '사무라이 여우 Akyo',
  探偵きつねAkyo: '탐정 여우 Akyo',
  // 0335 ケーキAkyo → same as 0141
  はにわAkyo: '하니와 Akyo',
  ライオンAkyo: '사자 Akyo',
  りゅうAkyo: '용 Akyo',
  おきつねAkyo: '오키츠네 Akyo',
  コロネAkyo: '코로네 Akyo',

  // === 0341–0350 ===
  富士山Akyo: '후지산 Akyo',
  弁当きつねAkyo: '도시락 여우 Akyo',
  サンドきつねAkyo: '샌드위치 여우 Akyo',
  お子様ランチAkyo: '어린이런치 Akyo',
  ダウンきつねAkyo: '패딩 여우 Akyo',
  まほうきつねAkyo: '마법 여우 Akyo',
  ハロウィンカボチャAkyo: '할로윈 호박 Akyo',
  まほうどらごんAkyo: '마법 드래곤 Akyo',
  セットどらごんAkyo: '세트 드래곤 Akyo',
  探偵どらごんAkyo: '탐정 드래곤 Akyo',

  // === 0351–0360 ===
  天使きつねAkyo: '천사 여우 Akyo',
  エゾAkyo: '에조 Akyo',
  コートきつねAkyo4: '코트 여우 Akyo 4',
  ツリーAkyo: '트리 Akyo',
  じゃがいもAkyo: '감자 Akyo',
  シャチAkyo: '범고래 Akyo',
  ないとどらごんAkyo: '나이트 드래곤 Akyo',
  風呂きつねAkyo: '목욕 여우 Akyo',
  キングAkyo: '킹 Akyo',
  振袖どらごんAkyo: '후리소데 드래곤 Akyo',

  // === 0361–0370 ===
  だるまAkyo: '달마 Akyo',
  トマトAkyo: '토마토 Akyo',
  リスAkyo: '다람쥐 Akyo',
  メロンソーダAkyo: '멜론소다 Akyo',
  赤べこAkyo: '아카베코 Akyo',
  嫁入りきつねAkyo: '시집가는 여우 Akyo',
  メロンAkyo: '멜론 Akyo',
  嫁入り婿きつねAkyo: '장가가는 여우 Akyo',
  つきそいきつねAkyo: '들러리 여우 Akyo',
  チョコAkyo: '초코 Akyo',

  // === 0371–0380 ===
  バナナAkyo: '바나나 Akyo',
  緑茶Akyo: '녹차 Akyo',
  ローダーAkyo: '로더 Akyo',
  キリンAkyo: '기린 Akyo',
  'ローダーAkyo2/ローダーきつねAkyo': '로더 Akyo 2/로더 여우 Akyo',
  天むすAkyo: '텐무스 Akyo',
  ハムスターAkyo: '햄스터 Akyo',
  スカーフきつねAkyo: '스카프 여우 Akyo',
  トーストきつねAkyo2: '토스트 여우 Akyo 2',
  いかAkyo: '오징어 Akyo',

  // === 0381–0390 ===
  くじらAkyo: '고래 Akyo',
  カエルAkyo: '개구리 Akyo',
  和メイドきつねAkyo: '화풍 메이드 여우 Akyo',
  'オコジョAkyo3.0': '족제비 Akyo 3.0',
  食パンAkyo: '식빵 Akyo',
  食パンきつねAkyo: '식빵 여우 Akyo',
  でんきゅうAkyo: '전구 Akyo',
  メロンパンAkyo: '멜론빵 Akyo',
  カステラAkyo2: '카스테라 Akyo 2',
  やきAkyo: '구이 Akyo',

  // === 0391–0400 ===
  'アーキョおじさん/おじAkyo': '아쿄 아저씨/아저씨 Akyo',
  ラムネAkyo: '라무네 Akyo',
  とのAkyo: '영주 Akyo',
  せんすいAkyo: '잠수 Akyo',
  カラス天狗Akyo: '까마귀 텐구 Akyo',
  くろねこAkyo: '검은고양이 Akyo',
  'ローダーAkyo3/ローダーくろねこAkyo': '로더 Akyo 3/로더 검은고양이 Akyo',
  さくらAkyo: '벚꽃 Akyo',
  おめんAkyo: '가면 Akyo',
  りきしAkyo: '스모선수 Akyo',

  // === 0401–0410 ===
  なつAkyo: '여름 Akyo',
  つりAkyo: '낚시 Akyo',
  モサモサAkyo: '텁수룩 Akyo',
  プリンきつねAkyo: '푸딩 여우 Akyo',
  水まんじゅうAkyo: '미즈만쥬 Akyo',
  'アキョベロス/ケルベロスAkyo': '아쿄베로스/케르베로스 Akyo',
  カフェきつねAkyo: '카페 여우 Akyo',
  がかきつねAkyo: '화가 여우 Akyo',
  白鳥Akyo: '백조 Akyo',
  陸戦型きつねAkyo: '육전형 여우 Akyo',

  // === 0411–0420 ===
  アカギツネAkyo: '붉은여우 Akyo',
  チベスナきつねAkyo: '티베트여우 Akyo',
  わさびAkyo: '와사비 Akyo',
  ビキニきつねAkyo: '비키니 여우 Akyo',
  フリル水着きつねAkyo: '프릴 수영복 여우 Akyo',
  豆腐AkyoA: '두부 Akyo A',
  豆腐AkyoB: '두부 Akyo B',
  みそしるAkyo: '된장국 Akyo',
  タピオカAkyo: '타피오카 Akyo',
  収穫祭Akyo: '수확제 Akyo',

  // === 0421–0430 ===
  はっぱAkyo: '나뭇잎 Akyo',
  ポンチョきつねAkyo: '판초 여우 Akyo',
  かき氷きつねAkyo: '빙수 여우 Akyo',
  りんごあめAkyo: '사과사탕 Akyo',
  サキュAkyo: '서큐 Akyo',
  いなりAkyo: '유부초밥 Akyo',
  八百屋ねぎAkyo: '채소가게 파 Akyo',
  農家ねぎAkyo: '농가 파 Akyo',
  ヤシAkyo: '야자 Akyo',
  レースきつねAkyo: '레이스 여우 Akyo',

  // === 0431–0440 ===
  駅員きつねAkyo: '역무원 여우 Akyo',
  バニーきつねAkyo: '버니 여우 Akyo',
  ストレッチAkyo: '스트레치 Akyo',
  あかずきんきつねAkyo: '빨간모자 여우 Akyo',
  りょうしAkyo: '사냥꾼 Akyo',
  しかAkyo: '사슴 Akyo',
  うたねぎAkyo: '노래 파 Akyo',
  うきょきつねAkyo: '우쿄 여우 Akyo',
  食パンたぬきAkyo: '식빵 너구리 Akyo',
  かにAkyo: '게 Akyo',

  // === 0441–0450 ===
  もちAkyo: '떡 Akyo',
  まほうねぎAkyo: '마법 파 Akyo',
  モンブランAkyo: '몽블랑 Akyo',
  モンブランきつねAkyo: '몽블랑 여우 Akyo',
  おおかみAkyo: '늑대 Akyo',
  宇宙Akyo: '우주 Akyo',
  ないときつねAkyo: '나이트 여우 Akyo',
  カボチャハロウィンAkyo: '호박 할로윈 Akyo',
  ハロウィンポンチョきつねAkyo: '할로윈 판초 여우 Akyo',
  キョンシーきつねAkyo: '강시 여우 Akyo',

  // === 0451–0460 ===
  ちゃがまたぬきAkyo: '찻주전자 너구리 Akyo',
  酒屋たぬきAkyo: '주점 너구리 Akyo',
  カフェおおかみAkyo: '카페 늑대 Akyo',
  どらごんAkyoSP: '드래곤 Akyo SP',
  木彫りきつねAkyo: '목조 여우 Akyo',
  ハロウィンだいこんAkyo: '할로윈 무 Akyo',
  オコジョAkyo2024: '족제비 Akyo 2024',
  こたつきつねAkyo: '코타츠 여우 Akyo',
  うまはにわAkyo: '말 하니와 Akyo',
  太陽の塔Akyo: '태양의 탑 Akyo',

  // === 0461–0470 ===
  はにわぶしAkyo: '하니와 무사 Akyo',
  アヌビスAkyo: '아누비스 Akyo',
  プリンカップAkyo: '푸딩컵 Akyo',
  えきいんおおかみAkyo: '역무원 늑대 Akyo',
  ゆきだるまきつねAkyo: '눈사람 여우 Akyo',
  まつのきAkyo: '소나무 Akyo',
  にわとりAkyo: '닭 Akyo',
  カレーAkyo: '카레 Akyo',
  サンタきつねAkyo: '산타 여우 Akyo',
  ふりそでおおかみAkyo: '후리소데 늑대 Akyo',

  // === 0471–0480 ===
  ふりそでたぬきAkyo: '후리소데 너구리 Akyo',
  // ふわふわAkyo → same as 0114
  こたつAkyo: '코타츠 Akyo',
  くまさん着ぐるみAkyo: '곰 인형옷 Akyo',
  囚人Akyo: '죄수 Akyo',
  なんかやばいAkyo: '뭔가 위험한 Akyo',
  キュクロープスAkyo: '키클롭스 Akyo',
  あきょのてせん: '아쿄의 철도',
  フェス気分のヤギAkyo: '페스 기분의 염소 Akyo',
  すし水勤務のAkyo: '초밥수족관 근무 Akyo',

  // === 0481–0490 ===
  ココナッツAkyo: '코코넛 Akyo',
  アスパラAkyo: '아스파라거스 Akyo',
  コーギーAkyo: '코기 Akyo',
  水兵きつねAkyo: '수병 여우 Akyo',
  ねぶくろAkyo: '침낭 Akyo',
  風邪ひきAkyo: '감기걸린 Akyo',
  ピカチュウAkyo: '피카츄 Akyo',
  ヒトカゲAkyo: '파이리 Akyo',
  ゼニガメAkyo: '꼬부기 Akyo',
  フシギダネAkyo: '이상해씨 Akyo',

  // === 0491–0500 ===
  NEET式泡Akyo: 'NEET식 거품 Akyo',
  アマダイAkyo: '옥돔 Akyo',
  ビードルAkyo: '뿔충이 Akyo',
  ヌオーAkyo: '누오 Akyo',
  コダックAkyo: '고라파덕 Akyo',
  りんごAkyo: '사과 Akyo',
  柿Akyo: '감 Akyo',
  ラテアートAkyo: '라떼아트 Akyo',
  リボンきつねAkyo: '리본 여우 Akyo',
  うたねぎAkyoB: '노래 파 Akyo B',

  // === 0501–0510 ===
  ねぶくろAkyo2: '침낭 Akyo 2',
  ねぶくろきつねAkyo: '침낭 여우 Akyo',
  銅像Akyo: '동상 Akyo',
  おきんきんAkyo: '금빛 Akyo',
  おきんきん蝶Akyo: '금빛 나비 Akyo',
  色彩反転Akyo: '색채반전 Akyo',
  // 0507 うさぎAkyo → same as 0180
  もふだいこんAkyo: '폭신 무 Akyo',
  シナモAkyo: '시나모 Akyo',
  ミサイルAkyo: '미사일 Akyo',

  // === 0511–0520 ===
  モーターAkyo: '모터 Akyo',
  にせムルルAkyo: '가짜 무루루 Akyo',
  まめひなたAkyo: '마메히나타 Akyo',
  VketちゃんAkyo: 'Vket쨩 Akyo',
  イーブイAkyo: '이브이 Akyo',
  モクリもどきAkyo: '모쿠리 모방 Akyo',
  キプフェルAkyo: '킵펠 Akyo',
  ワイトAkyo: '와이트 Akyo',
  ズバットAkyo: '주뱃 Akyo',
  ヒューマノイドもどきAkyo: '휴머노이드 모방 Akyo',

  // === 0521–0530 ===
  'ワーミ―Akyo': '워미 Akyo',
  義理チョコAkyo: '의리초코 Akyo',
  布ゴーストAkyo: '천 고스트 Akyo',
  ロボアームAkyo: '로봇팔 Akyo',
  二等辺三角形Akyo: '이등변삼각형 Akyo',
  キティAkyo: '키티 Akyo',
  カフェどらごんAkyo: '카페 드래곤 Akyo',
  サルAkyo: '원숭이 Akyo',
  うしAkyo2: '소 Akyo 2',
  ティラノAkyo2: '티라노 Akyo 2',

  // === 0531–0540 ===
  ウェディングきつねAkyo: '웨딩 여우 Akyo',
  ミャクミャクAkyo: '먀쿠먀쿠 Akyo',
  'R.I.P.Akyo': 'R.I.P. Akyo',
  墓石Akyo: '묘비 Akyo',
  リアル猫Akyo: '리얼 고양이 Akyo',
  BackRoomAkyo: 'BackRoom Akyo',
  ひなまつりおおかみAkyo: '히나마츠리 늑대 Akyo',
  魔法少女きつねAkyo: '마법소녀 여우 Akyo',
  うにAkyo: '성게 Akyo',
  どら焼きAkyo: '도라야키 Akyo',

  // === 0541–0550 ===
  オトモきつねAkyo: '오토모 여우 Akyo',
  山笠Akyo: '야마카사 Akyo',
  ダンシングアフロAkyo: '댄싱 아프로 Akyo',
  OrinaAkyon: 'Orina Akyon',
  アイルーもどきAkyo: '아이루 모방 Akyo',
  Akyo魔博士: 'Akyo마박사',
  手Akyo: '손 Akyo',
  '17HzAkyo': '17Hz Akyo',
  応力Akyo: '응력 Akyo',
  キリン装備きつねAkyo: '기린 장비 여우 Akyo',

  // === 0551–0560 ===
  デンタルAkyo: '덴탈 Akyo',
  シャトルAkyo: '셔틀 Akyo',
  RRどらごんAkyo: 'RR 드래곤 Akyo',
  ノワールAkyo: '누아르 Akyo',
  VRCTVAkyo: 'VRCTV Akyo',
  ソーダAkyo2: '소다 Akyo 2',
  カツサンドAkyo: '돈까스 샌드 Akyo',
  アキョウノトモシビ: '아쿄의 불빛',
  コロナAkyo: '코로나 Akyo',
  でかちちサキュバスAkyo: '거유 서큐버스 Akyo',

  // === 0561–0570 ===
  コンクリートAkyo: '콘크리트 Akyo',
  コンクリートAkyo2: '콘크리트 Akyo 2',
  オニフスベAkyo: '말불버섯 Akyo',
  ミニぐるみAkyo: '미니 인형 Akyo',
  お姫様Akyo: '공주 Akyo',
  フルフルAkyo: '후르후르 Akyo',
  消火器Akyo: '소화기 Akyo',
  頭文字Akyo: '이니셜 Akyo',
  ワープスターAkyo: '워프스타 Akyo',
  AkyoチキンAkyo: 'Akyo 치킨 Akyo',

  // === 0571–0580 ===
  食パンきつねAkyo2: '식빵 여우 Akyo 2',
  // 0572 りんごAkyo → same as 0496
  はちAkyo: '벌 Akyo',
  たこAkyo: '문어 Akyo',
  ありAkyo: '개미 Akyo',
  メロンパンかめAkyo: '멜론빵 거북이 Akyo',
  フランスパンAkyo: '바게트 Akyo',
  レインコートどらごんAkyo: '우비 드래곤 Akyo',
  もふひつじAkyo: '폭신 양 Akyo',
  ギャルAkyo: '갸루 Akyo',

  // === 0581–0590 ===
  霊夢Akyo: '레이무 Akyo',
  魔理沙Akyo: '마리사 Akyo',
  'Bault-Akyo': 'Bault-Akyo',
  骨Akyo: '뼈 Akyo',
  Zakyo: 'Zakyo',
  ピーマンAkyo: '피망 Akyo',
  コーヒーAkyo2: '커피 Akyo 2',
  胴長パグAkyo: '긴몸 퍼그 Akyo',
  ハウスネイルAkyo: '하우스네일 Akyo',
  川Akyo: '강 Akyo',

  // === 0591–0600 ===
  鯨肉Akyo: '고래고기 Akyo',
  // 0592 スイカAkyo → same as 0250
  ブレイドごっこAkyo: '블레이드 놀이 Akyo',
  ガンナーAkyo: '거너 Akyo',
  アーミーAkyo: '아미 Akyo',
  どんぐりAkyo: '도토리 Akyo',
  こころAkyo: '마음 Akyo',
  亜魚: '아어',
  亜魚露とル: '아어로틀',
  ミルクAkyo: '밀크 Akyo',

  // === 0601–0610 ===
  ウイスキーAkyo: '위스키 Akyo',
  ギャレンごっこAkyo: '갸렌 놀이 Akyo',
  着ぐるみAkyoくん: '인형옷 Akyo군',
  救急車ごっこAkyo: '구급차 놀이 Akyo',
  ウーパールーパーAkyo: '우파루파 Akyo',
  タコ皮Akyo: '문어 가죽 Akyo',
  ナナチもどきAkyo: '나나치 모방 Akyo',
  あきょざきしおり: '아쿄자키 시오리',
  ボンバーマンAkyo: '봄버맨 Akyo',
  ゆめかわユニコーンAkyo: '꿈꾸는 유니콘 Akyo',

  // === 0611–0620 ===
  着ぐるみお頭Akyo: '인형옷 물고기머리 Akyo',
  風船きつねAkyo: '풍선 여우 Akyo',
  どんぐりあきょー: '도토리 아쿄',
  珈琲豆あきょ: '커피콩 아쿄',
  らむねあきょ: '라무네 아쿄',
  精霊うまきょ: '정령 말쿄',
  'あきょりん・のーむ・ほーん': '아쿄린・노움・호른',
  鉛筆あきょ: '연필 아쿄',
  ヒョウモンダコAkyo: '파란고리문어 Akyo',
  'まめAkyo（ヤギ）': '콩 Akyo（염소）',

  // === 0621–0630 ===
  そらまめAkyo: '잠두콩 Akyo',
  柔らかいAkyo: '부드러운 Akyo',
  ミミックAkyo: '미믹 Akyo',
  ナイトキャップAkyo: '나이트캡 Akyo',
  ビッグボイン牛柄Akyo: '빅붕 젖소무늬 Akyo',
  牛乳を注ぐAkyo: '우유를 따르는 Akyo',
  箱Akyoダム: '상자 Akyo 댐',
  シャルベもどきAkyo: '샤루베 모방 Akyo',
  ラビットホールAkyo: '래빗홀 Akyo',
  歯磨き粉Akyo: '치약 Akyo',

  // === 0631–0640 ===
  段ボールナイトAkyo: '골판지 나이트 Akyo',
  冷蔵庫Akyo: '냉장고 Akyo',
  たれ耳うさぎAkyo: '늘어진귀 토끼 Akyo',
  たれ耳うさぎバニーAkyo: '늘어진귀 버니 Akyo',
  遺影ごっこAkyo: '영정사진 놀이 Akyo',
  もふもふライオンAkyo: '폭신폭신 사자 Akyo',
  マホロアもどきAkyo: '마호로아 모방 Akyo',
  マルクもどきAkyo: '마르크 모방 Akyo',
  自由のAkyo: '자유의 Akyo',
  まめがっぱあきょ: '콩 갓파 아쿄',

  // === 0641–0650 ===
  まめAkyo: '콩 Akyo',
  エプリAkyo: '에프리 Akyo',
  かっぱまきAkyo: '갓파마키 Akyo',
  キウイAkyo2: '키위 Akyo 2',
  ワンピースきつねAkyo2025: '원피스 여우 Akyo 2025',
  スポッティングルックAkyo: '스포팅 룩 Akyo',
  ウエスタンきつねAkyo: '웨스턴 여우 Akyo',
  まつぼっくりAkyo: '솔방울 Akyo',
  しゃけAkyo: '연어 Akyo',
  うAkyo: '우 Akyo',

  // === 0651–0660 ===
  エイAkyo: '가오리 Akyo',
  ももAkyo: '복숭아 Akyo',
  ハッシュAkyo: '해시 Akyo',
  アンチ浮動小数点Akyo: '안티 부동소수점 Akyo',
  クリオネAkyo: '클리오네 Akyo',
  蘇我高原Akyo: '소가고원 Akyo',
  わにAkyo: '악어 Akyo',
  ルーンAkyo: '룬 Akyo',
  ハロウィンきつねAkyo2025: '할로윈 여우 Akyo 2025',
  マスクおおかみAkyo: '마스크 늑대 Akyo',

  // === 0661–0670 ===
  ベニテングタケAkyo: '광대버섯 Akyo',
  ハロウィンメイドきつねAkyo: '할로윈 메이드 여우 Akyo',
  医者どらごんAkyo: '의사 드래곤 Akyo',
  ハロウィンにんじんAkyo: '할로윈 당근 Akyo',
  たまねぎAkyo: '양파 Akyo',
  'ルックAkyo？': '룩 Akyo？',
  ランチャームAkyo: '런치참 Akyo',
  風邪Akyo: '감기 Akyo',
  人面Akyo: '인면 Akyo',
  耳Akyo: '귀 Akyo',

  // === 0671–0680 ===
  多耳症Akyo: '다이증 Akyo',
  顔Akyo: '얼굴 Akyo',
  Agyo: 'Agyo',
  ウミガメAkyo: '바다거북 Akyo',
  'Akyo S': 'Akyo S',
  'Akyo J': 'Akyo J',
  虹Akyo: '무지개 Akyo',
  雨Akyo: '비 Akyo',
  うろAkyo: '우로 Akyo',
  'まめあきょだるま/だるままめAkyo': '콩 아쿄 달마/달마 콩 Akyo',

  // === 0681–0690 ===
  こまAkyo: '팽이 Akyo',
  ジンジャーブレッドAkyo: '진저브레드 Akyo',
  触れてはならないAkyo: '만져서는 안 되는 Akyo',
  マッスルキツネツキ式狐Akyo: '머슬 키츠네츠키식 여우 Akyo',
  たこやきAkyo: '타코야키 Akyo',
  'Skyo/空Akyo': 'Skyo/하늘 Akyo',
  aaaaAkyo: 'aaaa Akyo',
  空虚のAkyo: '공허의 Akyo',
  ボムAkyo: '폭탄 Akyo',
  えだまめAkyo: '에다마메 Akyo',

  // === 0691–0702 ===
  キバナヘイシソウAkyo: '노란환엽란 Akyo',
  'ゴッドまめAkyo/後光がなんかすごいまめAkyo': '갓 콩 Akyo/후광이 뭔가 대단한 콩 Akyo',
  後光がなんかヤバいAkyoULTIMATEエクストリームエディション:
    '후광이 뭔가 심상찮은 Akyo ULTIMATE 익스트림 에디션',
  鮎Akyo太郎: '은어 Akyo 타로',
  フィッシュボーンAkyo: '피시본 Akyo',
  おおかみセーターAkyo: '늑대 스웨터 Akyo',
  かぶとむしAkyo: '장수풍뎅이 Akyo',
  セーターぞうAkyo: '스웨터 코끼리 Akyo',
  'うまどしAkyo/正月うまAkyo': '말띠 Akyo/설날 말 Akyo',
  かもねぎAkyo: '오리파 Akyo',
  ダイヤAkyo: '다이아 Akyo',
  きつねまめAkyo: '여우콩 Akyo',

  // === 0703–0710 ===
  チーズAkyo: '치즈 Akyo',
  RGBダンスAkyo: 'RGB 댄스 Akyo',
  コズミックAkyo: '코즈믹 Akyo',
  クリスタルAkyo: '크리스탈 Akyo',
  赤チームのAkyo: '빨간 팀 Akyo',
  青チームのAkyo: '파란 팀 Akyo',
  アストラルAkyo: '아스트랄 Akyo',
  ホログラフィックAkyo: '홀로그래픽 Akyo',

  // === 0711–0720 ===
  クイーンAkyo: '퀸 Akyo',
  キツネツキ式雪狐Akyo: '키츠네츠키식 설여우 Akyo',
  ゴールデンキツネツキ式狐Akyo: '골든 키츠네츠키식 여우 Akyo',
  赤キツネツキ式グミ狐Akyo: '빨간 키츠네츠키식 젤리 여우 Akyo',
  青キツネツキ式グミ狐Akyo: '파란 키츠네츠키식 젤리 여우 Akyo',
  キツネツキ式パンク狐Akyo: '키츠네츠키식 펑크 여우 Akyo',
  赤キツネツキ式ジェム狐Akyo: '빨간 키츠네츠키식 젬 여우 Akyo',
  紫キツネツキ式ジェム狐Akyo: '보라 키츠네츠키식 젬 여우 Akyo',
  白キツネツキ式ジェム狐Akyo: '하얀 키츠네츠키식 젬 여우 Akyo',
  キツネツキ式アルミニウム狐Akyo: '키츠네츠키식 알루미늄 여우 Akyo',

  // === 0721–0730 ===
  キツネツキ式エーテリアル狐Akyo: '키츠네츠키식 에테리얼 여우 Akyo',
  電気ヒーターAkyo: '전기히터 Akyo',
  やきもちAkyo: '야키모치 Akyo',
  永久凍土Akyo: '영구동토 Akyo',
  カワウソAkyo: '수달 Akyo',
  インポスターAkyo: '임포스터 Akyo',
  'モヒカンAkyo/せいきまつAkyo': '모히칸 Akyo/세기말 Akyo',
  バターAkyo: '버터 Akyo',
  ピーナッツくんAkyo: '피넛츠군 Akyo',
  ぽんぽこAkyo: '폰포코 Akyo',

  // === 0731–0740 ===
  森のニジマスマンWith苔Akyo: '숲의 니지마스맨 With 이끼 Akyo',
  '絆の戦士・ウーパールーパーマン＆うまAkyo': '유대의 전사・우파루파맨 & 말 Akyo',
  'Akyoマン/Akyoヘッド': 'Akyo맨/Akyo헤드',
  レプタイルAkyo: '렙타일 Akyo',
  'たぬきまめAkyo/まめだぬきAkyo': '너구리콩 Akyo/콩너구리 Akyo',
  パンまめAkyo: '빵콩 Akyo',
  'もちまめAkyo/まめもちあきょ': '모찌콩 Akyo/콩모찌 아쿄',
  ふしAkyo: '후시 Akyo',
  'Akyo（第三世代）': 'Akyo (3세대)',

  // === 0740–0744 ===
  マンモスAkyo: '매머드 Akyo',
  アボカドAkyo: '아보카도 Akyo',
  カラフル回転Akyo: '컬러풀 회전 Akyo',
  たこまめAkyo: '문어콩 Akyo',
  赤サビAkyo: '붉은 녹 Akyo',
};

module.exports = { NICKNAME_MAP };
